on:
  push:
    branches: [master]
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          token: ${{ secrets.GIGANTIC_MEGA_PROJECT_GITHUB_TOKEN }}
          repository: Wing-summer/WingHexExplorer2
          path: .
